<a href="https://colab.research.google.com/github/manasa1311/abc/blob/main/experiment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
#load the datset
dataset=pd.read_csv("/content/age_sal_dataset.csv")
#printing the dataset
dataset

     Age   Salary
0   45.0  55000.0
1   34.0  65000.0
2    NaN  40000.0
3   35.0      NaN
4   49.0  65000.0
5    NaN  45000.0
6    NaN      NaN
7   22.0  25000.0
8   30.0  30000.0
9   35.0  32000.0
10   NaN  44000.0

In [23]:
#Extraction of independent and dependent variables
X= dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values
print("independent variable(X):",X)
print("Dependent variable (Y)",Y)

independent variable(X): [[45.]
 [34.]
 [nan]
 [35.]
 [49.]
 [nan]
 [nan]
 [22.]
 [30.]
 [35.]
 [nan]]
Dependent variable (Y) [55000. 65000. 40000.    nan 65000. 45000.    nan 25000. 30000. 32000.
 44000.]

In [24]:
#dealing with missing data
from sklearn.impute import SimpleImputer
#REPLACING MISSING VALUES USING TRANSFORM METHOD
imp=SimpleImputer(missing_values=np.nan, strategy="mean")
X=imp.fit_transform(X)
Y=Y.reshape(-1,1)
Y=imp.fit_transform(Y)
Y=Y.reshape(-1)
print(X)
print(Y)

[[45.        ]
 [34.        ]
 [35.71428571]
 [35.        ]
 [49.        ]
 [35.71428571]
 [35.71428571]
 [22.        ]
 [30.        ]
 [35.        ]
 [35.71428571]]
[55000.         65000.         40000.         44555.55555556
 65000.         45000.         44555.55555556 25000.
 30000.         32000.         44000.        ]

In [25]:
#covert X to Y to DataFrames
X_df=pd.DataFrame(X, columns=dataset.columns[:-1])
Y_df=pd.DataFrame(Y, columns=[dataset.columns[-1]])
#combine X and Y using pandas.concat
combined_data=pd.concat([X_df, Y_df], axis=1)
print("Combined Data:")
print(combined_data)

Combined Data:
          Age        Salary
0   45.000000  55000.000000
1   34.000000  65000.000000
2   35.714286  40000.000000
3   35.000000  44555.555556
4   49.000000  65000.000000
5   35.714286  45000.000000
6   35.714286  44555.555556
7   22.000000  25000.000000
8   30.000000  30000.000000
9   35.000000  32000.000000
10  35.714286  44000.000000

In [26]:
combined_df=pd.DataFrame(combined_data,columns=list(dataset.columns))
combined_df.to_excel("/content/combined_data.xlsx",index=False)
print("combined dataframe")
print(combined_df.head())

combined dataframe
         Age        Salary
0  45.000000  55000.000000
1  34.000000  65000.000000
2  35.714286  40000.000000
3  35.000000  44555.555556
4  49.000000  65000.000000